### ISSUE TITLE
After upgrading to 2.0.2 release ValueProviderSupport class is not longer supported

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#238]
Hello,

After upgrading to version 2.0.2 import org.springframework.shell.standard.ValueProviderSupport class can not be resolved anymore.
Is this a bug or  is it intentionally done ? If yes, what is the most close alternative to this ?

Thank you!
Thanasis

**Comment by fonimus** [comment]
Hello, the new release of this project in 2.0.0 comes with lots of breaking changes due to changes in spring shell project.
You can check the new documentation here : https://docs.spring.io/spring-shell/docs/2.1.1/site/reference/htmlsingle/#_interactive but the new way is to implement interface org.springframework.shell.standard.ValueProvider

I also have examples in the code (ex here : https://github.com/fonimus/ssh-shell-spring-boot/blob/main/samples/complete/src/main/java/com/github/fonimus/ssh/shell/complete/CompleteCommands.java)

**Comment by ThanasisBarekas** [comment]
Thank you for your prompt support on this!
